name: Daily Bash Job

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run bash script
        env:
          X_LONGZHU_SIGN: ${{ secrets.X_LONGZHU_SIGN }}
          LM_TOKEN: ${{ secrets.LM_TOKEN }}
        run: |
          chmod +x ./longfor_task.sh
          ./longfor_task.sh 2>&1 | tee output.log
          
      - name: Send log to Feishu
        run: |
          LOG=$(cat output.log)

          JSON=$(jq -n --arg text "$LOG" '{
              msg_type: "text",
              content: { text: ("📄 签到:\n" + $text) }
            }')

          curl -X POST "${{ secrets.FEISHU_WEBHOOK }}" \
            -H "Content-Type: application/json" \
            -d "$JSON"

