name: Daily Bash Job

on:
  schedule:
    - cron: '0 0 * * *'
  workflow_dispatch:

jobs:
  run-bash:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Run bash script
        env:
          X_LONGZHU_SIGN: ${{ secrets.X_LONGZHU_SIGN }}
          LM_TOKEN: ${{ secrets.LM_TOKEN }}
        run: |
          chmod +x ./longfor_task.sh
          ./longfor_task.sh

